[package]
name = "taxonia-service"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8"
tokio = { version = "1", features = ["full"] }
sqlx = { version = "0.8", features = ["postgres", "runtime-tokio-rustls"] }
dotenvy = "0.15"
tracing-subscriber = "0.3"
anyhow = "1.0.98"
